## Numpy Library Exercises

In [3]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [3]:
# your code
arr = np.random.randint(20, size=20)
arr

result = np.where((arr >= 3) & (arr <= 8), -arr, arr)
result


array([12, -6,  2, -6, 10, -6, -6, 11, 11, 19, 17, -5, -7, 11, 17, 15, 15,
       15, -5, -3])

**2.** Replace the maximum element of a random array with 0

In [4]:
# your code
arr[arr == arr.max()] = 0
arr

array([12,  6,  2,  6, 10,  6,  6, 11, 11,  0, 17,  5,  7, 11, 17, 15, 15,
       15,  5,  3])

**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [5]:
# your code
arr1 = np.arange(5)
arr2 = np.arange(5)

np.outer(arr1, arr2)

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [27]:
# your code
A = np.random.randint(20, size=24).reshape(8,3)
B = np.random.randint(20, size=4).reshape(2,2)


indices = np.where(np.column_stack([np.isin(A, row).any(axis=1) for row in B]).all(axis=1))[0]
rows = A[indices]

A, B, indices, rows

(array([[ 8, 16,  1],
        [ 2, 19,  4],
        [13, 12,  0],
        [ 2, 15, 18],
        [11, 17, 14],
        [10,  8, 18],
        [ 7, 12,  0],
        [14, 14,  8]]),
 array([[15,  6],
        [14,  2]]),
 array([3], dtype=int64),
 array([[ 2, 15, 18]]))

**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [28]:
# your code
arr3 = np.random.randint(3, size=30).reshape(10,3)

all_equal = np.all(arr3 == arr3[:, [0]], axis=1)
unequal_rows = arr3[~all_equal]

arr3, unequal_rows

(array([[0, 0, 2],
        [0, 0, 2],
        [2, 1, 0],
        [1, 0, 2],
        [1, 2, 2],
        [1, 1, 2],
        [2, 2, 0],
        [1, 0, 1],
        [1, 2, 1],
        [2, 1, 2]]),
 array([[0, 0, 2],
        [0, 0, 2],
        [2, 1, 0],
        [1, 0, 2],
        [1, 2, 2],
        [1, 1, 2],
        [2, 2, 0],
        [1, 0, 1],
        [1, 2, 1],
        [2, 1, 2]]))

**6.** Given a two-dimensional array, remove the rows that are repeated.

In [8]:
# your code
arr4 = np.random.randint(3, size=10).reshape(5,2)

result, counts = np.unique(arr4, axis=0, return_counts=True)

arr4, result[counts == 1]

(array([[1, 2],
        [1, 1],
        [0, 0],
        [2, 2],
        [1, 2]]),
 array([[0, 0],
        [1, 1],
        [2, 2]]))

______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [34]:
# your code
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
diag = np.diagonal(X)
res = np.prod(diag[diag != 0])
res

3

In [10]:
X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
prod = 1
for i in range(3):
    if X[i][i]>0:
        prod *= X[i][i]
prod

3

* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [11]:
# your code
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

y.sort()
(x == y).all()


True

In [12]:
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

y.sort()
x == y

True

* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [13]:
# your code
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
zero = (x[:-1] == 0)
result = (x[1:][zero]).max()

result

5

In [14]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

value = min(x)

for i in range(len(x)):
    if x[i] > value and x[i-1] == 0 and i-1 > 0:
        value = x[i]

value

5

* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [15]:
# your code
x = np.array([2, 2, 2, 3, 3, 3, 5])

counts = np.diff(np.append(np.append(-1, np.where(x[:-1] != x[1:])[0]  ), len(x) - 1))
values = x[np.append(0, np.where(x[:-1] != x[1:])[0] + 1)]

values, counts

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))

In [16]:
x = [2, 2, 2, 3, 3, 3, 5]

values = [x[0]]
counts = [1]

for item in x[1:]:
    if item == values[-1]:
        counts[-1] += 1
    else:
        values.append(item)
        counts.append(1)

values, counts

([2, 3, 5], [3, 3, 1])

* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [17]:
# your code
X = np.random.randint(10, size=9).reshape(3,3)
Y = np.random.randint(10, size=9).reshape(3,3)

distance = np.sqrt(np.sum((X[:, np.newaxis, :] - Y[np.newaxis, :, :]) ** 2, axis=-1))
distance

array([[ 9.11043358,  4.24264069,  3.74165739],
       [ 6.70820393,  6.63324958,  7.34846923],
       [10.24695077,  4.47213595,  8.60232527]])

In [18]:
import math

matrix = []
    
for x in X:
    row = []
    for y in Y:
        diff = sum((x - y) ** 2 for x, y in zip(x, y))
        distance = math.sqrt(diff)
        row.append(distance)
    matrix.append(row)

matrix

[[9.1104335791443, 4.242640687119285, 3.7416573867739413],
 [6.708203932499369, 6.6332495807108, 7.3484692283495345],
 [10.246950765959598, 4.47213595499958, 8.602325267042627]]

_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [19]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [20]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [21]:
# your code
average_calories = np.mean(calorie_stats)
average_calories - 60 

46.883116883116884

3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [22]:
# your code
calorie_stats_sorted = np.sort(calorie_stats, axis=0)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [23]:
# your code
median_calories = np.median(calorie_stats)
median_calories

110.0

5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [24]:
# your code
nth_percentile = 0
for n in range(1, 100):
    value = np.percentile(calorie_stats, n)
    print(value)
    if value > 60:
        nth_percentile = n
        break

50.0
50.0
55.599999999999994
70.0


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [25]:
# your code
more_calories = (calorie_stats > 60).mean()
more_calories


0.961038961038961

7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [26]:
# your code
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [27]:
# your code

print(f' Средние калории = {average_calories}, Медианные калории = {median_calories}, Перцентиль = {nth_percentile}, Процент = {more_calories}, Разброс = {calorie_std}')
#Средние калории конкурентов ~106, что на 46 больше, чем у CrunchieMunchies. Половина порций конкурентов имеет кол-во калорий более 110. 
# При пересчете на проценты, порции компаний-конкурентов в 96% случаев имеют калории больше, чем у CrunchieMunchies.


 Средние калории = 106.88311688311688, Медианные калории = 110.0, Перцентиль = 4, Процент = 0.961038961038961, Разброс = 19.35718533390827
